### PR TITLE
Add New ESP Line Thickness

### PR DESCRIPTION
**Pull request by WYLDYR**
Very basic change.
It's just a lil change
I'll make some bigger things later just wanted to do something

Basically just a little widget in the ESP tab to increase and decrease the width of tracer lines.
Also. Are some of the plugins useless? I feel that some don't work or don't serve a purpose.

### CODE REVIEW

**Comment by humphreygaming** [comment]
most plug-in's aren't useless unless you are talking about auto dodge + other things

**Comment by WYLDYR** [comment]
old-loot.js doesn't have an implementation, theme.js doesn't work as of recent, bumpfire.js has no run loop.

Also, I have some more visual options on the way if you could pls commit them

**Comment by 068scar** [comment]
@WYLDYR  stfu and stop hacking noob

**Comment by humphreygaming** [comment]
shut it, pathetic pussy. You are the one who "made a surviv hack", showcased it, and now turned into a bitch about it saying "bUT i cHAnGEd". shut the fuck up

**Comment by 068scar** [comment]
yep its better if u chenge aswell

**Pull request merged**
